export function wordle(gamesContainer, gameFinishedCallback) {
    let gameFinished = false;
    const words = ["Apple", "Bread", "Chair", "Dance", "Eagle", "Frost", "Grain", "House", "Jelly", "Kites",
        "Lemon", "Magic", "Night", "Ocean", "Peach", "Quiet", "River", "Story", "Tiger", "Uncle",
        "Value", "Water", "Xerox", "Yield", "Zebra", "Angel", "Brave", "Crowd", "Dream", "Earth",
        "Field", "Giant", "Heart", "Ideal", "Jolly", "Karma", "Light", "Music", "North", "Olive",
        "Plane", "Queen", "Rocky", "Shine", "Thumb", "Usual", "Voice", "Wheat", "Xylol", "Young",
        "Alloy", "Bloom", "Clear", "Drift", "Every", "Fancy", "Ghost", "Happy", "Image", "Joint",
        "Knife", "Latch", "Magic", "Novel", "Oasis", "Peace", "Quiet", "Rogue", "Share", "Throw",
        "Unity", "Vivid", "Whirl", "Xylem", "Yearn", "Zesty", "Alert", "Batch", "Clean", "Dryly",
        "Eager", "Flake", "Great", "Hinge", "Index", "Joker", "Layer", "Mirth", "Niche", "Onset",
        "Prawn", "Query", "Ridge", "Shine", "Trend", "Upper", "Verge", "Whale", "Xylic", "Youth",
        "Azure", "Brick", "Craft", "Depth", "Equip", "Feast", "Glory", "Hotel", "Inlet", "Jumpy"];
    const correctWord = words[Math.floor(Math.random() * words.length)].toLowerCase();

    gamesContainer.innerHTML = `
    <div id="game">
        <div id="board">
            <!-- Rows and cells are dynamically generated by JavaScript -->
        </div>
        <input type="text" id="guess-input" maxlength="5" autofocus>
        <button id="submit-guess">Submit Guess</button>
    </div>
    `;

    let currentRow = 0;

    // Generate the board
    const board = document.getElementById('board');
    for (let i = 0; i < 30; i++) {
        const cell = document.createElement('div');
        cell.className = 'cell';
        board.appendChild(cell);
    }

    const submitButton = document.getElementById('submit-guess');
    const guessInput = document.getElementById('guess-input');

    function handleGuess() {
        const guess = guessInput.value.toLowerCase();
        if (guess.length !== 5) {
            alert('Please enter a five-letter word.');
            return;
        }

        const rowStartIndex = currentRow * 5;
        for (let i = 0; i < 5; i++) {
            const cell = board.children[rowStartIndex + i];
            cell.textContent = guess[i];

            if (guess[i] === correctWord[i]) {
                cell.classList.add('correct');
            } else if (correctWord.includes(guess[i])) {
                cell.classList.add('present');
            } else {
                cell.classList.add('absent');
            }
        }

        if (guess === correctWord) {
            submitButton.disabled = true;
            gamesContainer.innerHTML = `<p id="correctGuess">Congratulations! You guessed the right word!</p>`;
            gameFinished = true;
            setTimeout(() => {
                gameFinishedCallback(gameFinished);
            }, 2000);
        } else if (currentRow === 5) {
            submitButton.disabled = true;
            gamesContainer.innerHTML = `<p id="wrongGuess">Game over! The right word was ${correctWord}</p>`;
            gameFinished = true;
            setTimeout(() => {
                gameFinishedCallback(gameFinished);
            }, 2000);
        }

        currentRow++;
        guessInput.value = '';
    }

    submitButton.addEventListener('click', handleGuess);

    guessInput.addEventListener('keyup', (event) => {
        if (event.key === 'Enter') {
            handleGuess();
        }
    });

    return gameFinished;
}